#!/bin/bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "${SCRIPT_DIR}/.."

toolchain=$(rustup toolchain list | grep active | awk '{print $1}')

DYLD_FALLBACK_LIBRARY_PATH=$HOME/.rustup/toolchains/$toolchain/lib/rustlib/aarch64-apple-darwin/lib:./target/release/deps ./target/release/bevy-fluid-sim "$@"
